### ISSUE TITLE
Any compact mechanism on titan's manifest file ?

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/titan#288]
We have been running the TiKV cluster online for a long time, and the manifest file of Titan has reached the level of nearly 200GB. It takes 10-15 minutes to initialize titan during each tikv startup~

What confuses me is that some clusters have enabled titan but have no large value at all. There are no blob files in titan, but Titan's manifest has also reached 100GB

**Comment by Connor1996** [comment]
Titan doesn't have a manifest rotate mechanism now. Would you like to file a PR to support it?

As for the large manifest, it's probably due to too many empty version edits with no blob file add/remove. It's avoided by https://github.com/tikv/titan/pull/283/files#diff-048e2f2f503496399017e1db5c4403052896100543b9b3d88784d79fc373acf8R68. What's the commit are you using?

**Comment by mzygQAQ** [comment]
Reopen, i found the reason,  the DeleteBlobFilesInRange will issue an VersionEdit even if no files deleted,  i will propose a pr later sonn.
